### ISSUE TITLE
0xbepresent - The liquidatable position can be closed before someone liquidates it causing that the liquidation penalty to be evaded

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#125]
0xbepresent

high

# The liquidatable position can be closed before someone liquidates it causing that the liquidation penalty to be evaded

## Summary

The liquidatable position can be closed using the [Vault.close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) function causing the evasion of the [liquidation penalty](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L368-L373).

## Vulnerability Detail

The [Vault.liquidate()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L346) function helps to liquidate a liquidatable position. The function makes the next executions:
1. It calculates the [min_amount_out](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L359) based on the position debt and position amount.
2. Then [it closes the position](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L363) using the `Vault._close_position()` function.
3. If there is enough amount_out_received, [it charges a penalty](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L368-L373) to the account's margin.

The problem is that the user account can call directly the [Vault.close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) before someone liquidates him. I created the next test where the position is closed before someone can liquidates it:

```python
# tests/vault/test_liquidate.py
# $ pytest -k "test_close_position_before_get_liquidated"
def test_close_position_before_get_liquidated(
    vault, owner, alice, weth, usdc, eth_usd_oracle
):
    """
    Close the position before it get liquidated so the penalty can be evaded
    """
    #
    # 1. Open a position
    #
    position_uid, _ = open_position(vault, owner, weth, usdc)
    eth_usd_oracle.set_answer(1234_0000_0000)
    # we have have a margin of 10USDC, borrow 90 and buy for 100 thus
    # our effective leverage is 10 as we have 10 times our margin-value in ETH
    assert vault.effective_leverage(position_uid) == 10
    eth_usd_oracle.set_answer(1135_0000_0000)
    #
    # 2. Position is liquidable right now
    #
    assert vault.effective_leverage(position_uid) == 51
    assert vault.is_liquidatable(position_uid) == True
    #
    # 3. Close position before someone liquidates it so the penalty can be evaded
    #
    vault.close_position(position_uid, 0)
    assert vault.positions(position_uid)[1:] == (
        "0x0000000000000000000000000000000000000000",
        "0x0000000000000000000000000000000000000000",
        0,
        0,
        "0x0000000000000000000000000000000000000000",
        0,
    )
```

## Impact

The position can be closed before someone can liquidates it causing the user account can evade the liquidation penalty so those penalties are lost.

## Code Snippet

- The [Vault.liquidate()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L346) function.
- The [Vault.close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) function.

## Tool used

Manual review

## Recommendation

The external [Vault.close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) function should be called only if the position is not liquidatable.

```diff
def close_position(_position_uid: bytes32, _min_amount_out: uint256) -> uint256:
    assert self.is_whitelisted_dex[msg.sender], "unauthorized"
++  assert not self._is_liquidatable(_position_uid), "in liquidation" 
    return self._close_position(_position_uid, _min_amount_out)
```

**Comment by 0xbepresent** [comment]
Escalates

I consider this is still valid concern. If the liquidated user can not repay his own debt, he can decide to accept losses and close his own position via [Vault.close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) causing the evasion of the [protocol penalty fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L366-L373) (code line 372).

```python
File: Vault.vy
365:     # penalize account
366:     penalty: uint256 = debt_amount * self.liquidation_penalty / PERCENTAGE_BASE
367: 
368:     if amount_out_received > debt_amount:
369:         # margin left
370:         remaining_margin: uint256 = amount_out_received - debt_amount
371:         penalty = min(penalty, remaining_margin)
372:         self.margin[position.account][position.debt_token] -= penalty
373:         self._distribute_trading_fee(position.debt_token, penalty)
```
So, [protocol and LPs lost those liquidation fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1342-L1356). The liquidable user is incentivized to close his own position (with losses) in order to not be charged the liquidation penalty fees.

Considering that liquidation engine is run by the protocol team https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650, those fees must be collected

**Comment by sherlock-admin2** [comment]
> Escalates
> 
> I consider this is still valid concern. If the liquidated user can not repay his own debt, he can decide to accept losses and close his own position via [Vault.close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) causing the evasion of the [protocol penalty fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L366-L373) (code line 372).
> 
> ```python
> File: Vault.vy
> 365:     # penalize account
> 366:     penalty: uint256 = debt_amount * self.liquidation_penalty / PERCENTAGE_BASE
> 367: 
> 368:     if amount_out_received > debt_amount:
> 369:         # margin left
> 370:         remaining_margin: uint256 = amount_out_received - debt_amount
> 371:         penalty = min(penalty, remaining_margin)
> 372:         self.margin[position.account][position.debt_token] -= penalty
> 373:         self._distribute_trading_fee(position.debt_token, penalty)
> ```
> So, [protocol and LPs lost those liquidation fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1342-L1356). The liquidable user is incentivized to close his own position (with losses) in order to not be charged the liquidation penalty fees.
> 
> Considering that liquidation engine is run by the protocol team https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650, those fees must be collected 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 141345** [comment]
Recommendation: 
keep the original judging.


> Escalates
> 
> I consider this is still valid concern. If the liquidated user can not repay his own debt, he can decide to accept losses and close his own position via [Vault.close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) causing the evasion of the [protocol penalty fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L366-L373) (code line 372).
> 
> ```python
> File: Vault.vy
> 365:     # penalize account
> 366:     penalty: uint256 = debt_amount * self.liquidation_penalty / PERCENTAGE_BASE
> 367: 
> 368:     if amount_out_received > debt_amount:
> 369:         # margin left
> 370:         remaining_margin: uint256 = amount_out_received - debt_amount
> 371:         penalty = min(penalty, remaining_margin)
> 372:         self.margin[position.account][position.debt_token] -= penalty
> 373:         self._distribute_trading_fee(position.debt_token, penalty)
> ```
> 
> So, [protocol and LPs lost those liquidation fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1342-L1356). The liquidable user is incentivized to close his own position (with losses) in order to not be charged the liquidation penalty fees.
> 
> Considering that liquidation engine is run by the protocol team [#146 (comment)](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650), those fees must be collected

Users can repay debt to close the position, it's the normal operation. The exchange's goal is not to punish underwater users. The first priority is to manage risk, as long as the position debt is repaid, the risk level is under control.

**Comment by 0xbepresent** [comment]
FYI

The protocol has a validation in the [reduce_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L301) function to check if the position is liquidatable. The same validation should be in the [close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) function so the positions that are liquidatable pay penalty fees.

Of course, the user debt will be repaid either via liquidate() or close_position(), **the concern here is that the protocol and LPs won't collect penalty fees** if users uses the close_position() function AND their positions are unhealthy positions (liquidable positions).

Thanks for your time.

**Comment by 141345** [comment]
> FYI
> 
> The protocol has a validation in the [reduce_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L301) function to check if the position is liquidatable. The same validation should be in the [close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L227) function so the positions that are liquidatable pay penalty fees.
> 
> Of course, the user debt will be repaid either via liquidate() or close_position(), **the concern here is that the protocol and LPs won't collect penalty fees** if users uses the close_position() function AND their positions are unhealthy positions (liquidable positions).
> 
> Thanks for your time.

Like the reason above, penalty fee is not the goal. The goal is maintaining financially healthy system. The idea is similar to lending protocol, even a user is underwater, eligible for liquidation, the user can still repay the debt asap to avoid the liquidation and fee.

**Comment by 0xbepresent** [comment]
Thanks for your response!. 

The close_position() does not ensure that the debt will be paid. Actually there are scenarios where the debt will not to be paid and the system enters in [bad debt or defensive mode](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L264-L272).

The user can use [add_margin()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L503) in order to avoid liquidation and fee.

Please see the next scenario:
1. User is underwater and he use close_position() because he does not have money to add more margin.
2. The system will be in [bad debt](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L264) because position assets don't cover the debt.
3. Protocol and LPs lost liquidations fees since user decided to use close_position(). If user wants to avoid liquidation he should use add_margin(). If user wants to close his position, it is possible but since the position is liquidable, the [liquidate()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L346) should be used in order to collect fees.

[Protocol and LPs will lost those penalty fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L373) so I still think it is at least Medium since there is possible material of loss.

**Comment by 141345** [comment]
> The close_position() does not ensure that the debt will be paid. Actually there are scenarios where the debt will not to be paid and the system enters in [bad debt or defensive mode](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L264-L272).

Right, this is possilbe scenario. But I think it's different issue.
Because if this happens, the position is already deep underwater, the position_token depreciates a lot, cannot swap enough debt_token amount. The problem should be: why the liquidation bot did not handle the position beforehand? 


Come back to this one, here the focus is: whether the penalty fee is a must?

My opinion is no. Because the protocol and LP do not rely on the penalty as income, risk control is the priority, whatever method. If the user repay in full it shall be fine.


> The user can use [add_margin()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L503) in order to avoid liquidation and fee.
> Please see the next scenario:

Usually add margin is cheaper than repay in full, since the margin comes with leverage.

**Comment by 0xbepresent** [comment]
I'm not sure what is the "risk management" you mention. I mean, at the end the `close_position()` function swaps tokens and repay the debt with [the swapped tokens](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L259), so the protocol risk is controlled.

- If the user close his **liquidable position** via `close_position()`, the [_close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L233-L279) is executed.
- If liquidation bot close the **user liquidable position** via `liquidate()`, it will execute the same [_close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L363) function plus the [liquidation penalty fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L372) extraction.

So at the end, the liquidable user and liquidator execute the same `_close_position()` function and the risk is controlled. The issue reported here is that an **user can evade those liquidation penalty fees** by chance or via frontrunning.

Considering that the protocol team [wants to incentive his own liquidation engine](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650), yes I consider a charge liquidation penalty fees is a must.

This is my last comment since I don't have nothing more to add. Thanks for your time.

**Comment by 141345** [comment]
> I'm not sure what is the "risk management" you mention. I mean, at the end the `close_position()` function swaps tokens and repay the debt with [the swapped tokens](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L259), so the protocol risk is controlled.
> 
> * If the user close his **liquidable position** via `close_position()`, the [_close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L233-L279) is executed.
> * If liquidation bot close the **user liquidable position** via `liquidate()`, it will execute the same [_close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L363) function plus the [liquidation penalty fees](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L372) extraction.
> 
> So at the end, the liquidable user and liquidator execute the same `_close_position()` function and the risk is controlled. The issue reported here is that an **user can evade those liquidation penalty fees** by chance or via frontrunning.
> 
> Considering that the protocol team [wants to incentive his own liquidation engine](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650), yes I consider a charge liquidation penalty fees is a must.
> 
> This is my last comment since I don't have nothing more to add. Thanks for your time.

The controversy is about penalty fee. 
Similar situation, some lending platform also have liquidation penalty, but can repay asap to avoid the penalty.

Let's see Sherlock's decision on this topic.

**Comment by hrishibhat** [comment]
Result:
Low
Unique. 
Agree with the Lead judge comments. Additional comments from the Sponsor:
> This is by design. To keep the system and protocol healthy a liqudiatable position needs to be closed. If the user does it before the liquidation engine or a bot, that's still good for the protocol and keeps it healthy.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xbepresent](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/125/#issuecomment-1644562415): rejected
