### ISSUE TITLE
0xbepresent - If the protocol is in defensive mode `is_accepting_new_orders is False` the users are unable to fund their account and to be unable to add margin to their positions

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#128]
0xbepresent

high

# If the protocol is in defensive mode `is_accepting_new_orders is False` the users are unable to fund their account and to be unable to add margin to their positions

## Summary

When a position is in bad debt, all the protocol is set defensive mode 'is_accepting_new_orders is False' causing that users can't fund their margin and to be unable to cover their margin positions, so this situation obligate them to reduce their positions in order to not be liquidatable.

## Vulnerability Detail

The protocol can be in [defensive mode](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L266) when one position enters in bad debt. Once the protocol is in defensive mode `is_accepting_new_orders is False` the next functions are disabled:

- [Vault.open_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L171)
- [Vault.fund_account_eth()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L664)
- [Vault.fund_account()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L673)
- [Vault.provide_liquidity_eth()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L767C5-L767C26)
- [Vault.provide_liquidity()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L786C5-L786C22)

The problem is that an user can't add funds to their margin account using the [Vault.fund_account()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L673) or [Vault.fund_account_eth()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L664) functions. So this causes that the user may not have margin to add to their position using the [Vault.add_margin()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L503C5-L503C15) function. This situation obligate them to reduce their position in order to not be liquidatable.

I created a test where the `fund_account()` function is not available once the system enters in defensive mode 'is_accepting_new_orders is False'

```python
# tests/vault/test_close_position.py
# $ pytest -k "test_close_position_in_bad_debt_deactivates_accepting_new_orders_and_fund_account"
def test_close_position_in_bad_debt_deactivates_accepting_new_orders_and_fund_account(
    vault, usdc, weth, owner, alice
):
    """
    When a position is in bad debt, all the protocol is set defensive mode 'is_accepting_new_orders is False'
    causing that users can't fund their margin and be unable to cover their margin positions, so this situation
    obligate them to reduce their positions in order to not be liquidatable.
    """
    #
    # 1. Create the position and put it in bad debt, so the is_accepting_new_orders is desactivated
    #
    position_uid, _ = open_position(vault, owner, weth, usdc)
    assert vault.is_accepting_new_orders()
    vault.positions(position_uid)
    vault.close_position(position_uid, 0)  # 0 out
    bad_debt_after = vault.bad_debt(usdc)
    assert bad_debt_after > 0
    assert vault.is_accepting_new_orders() is False
    #
    # 2. The fund account is not available any more
    #
    with boa.env.prank(alice):
        with boa.reverts("funding paused"):
            vault.fund_account(usdc, 1)
```

## Impact

When the system is in `defensive mode` the users are unable to fund their accounts, then the users are obligated to reduce their position in order the avoid the liquidation. Users can lost their positions if they enter in panic and they can not fund their margin accounts.

## Code Snippet

- The [Vault._close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L233) function which sets the system in [defensive mode](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L266) if there is a bad debt.

## Tool used

Manual review

## Recommendation

The easier solution is to avoid liquidations while the system is in `defensive mode`.

**Comment by 0xbepresent** [comment]
Escalate

I still consider this is a real issue for users. The [close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L233) is possible but it cause some problems:
- The user [interests debt](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L251) might be unfair since the debt interests are calculated based on the [token utilization rate](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1173). So users may not want to pay the interest at that time
- Close the position and then open the position again when the system is not in `defensive mode` will incur in to [pay "open position" fees again](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L201-L204). 

Allowing users to put margin would be fair and easier to users because otherwise they need to pay fees again in order to open the same position.

There are some references about this bug in [Perennial](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/190) and [Notional](https://github.com/sherlock-audit/2023-03-notional-judging/issues/203)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I still consider this is a real issue for users. The [close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L233) is possible but it cause some problems:
> - The user [interests debt](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L251) might be unfair since the debt interests are calculated based on the [token utilization rate](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1173). So users may not want to pay the interest at that time
> - Close the position and then open the position again when the system is not in `defensive mode` will incur in to [pay "open position" fees again](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L201-L204). 
> 
> Allowing users to put margin would be fair and easier to users because otherwise they need to pay fees again in order to open the same position.
> 
> There are some references about this bug in [Perennial](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/190) and [Notional](https://github.com/sherlock-audit/2023-03-notional-judging/issues/203)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 141345** [comment]
Recommendation: 
keep the original judging.


> Escalate
> 
> I still consider this is a real issue for users. The [close_position()](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L233) is possible but it cause some problems:
> 
> * The user [interests debt](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L251) might be unfair since the debt interests are calculated based on the [token utilization rate](https://github.com/sherlock-audit/2023-06-unstoppable/blob/94a68e49971bc6942c75da76720f7170d46c0150/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1173). So users may not want to pay the interest at that time
> * Close the position and then open the position again when the system is not in `defensive mode` will incur in to [pay "open position" fees again](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L201-L204).
> 
> Allowing users to put margin would be fair and easier to users because otherwise they need to pay fees again in order to open the same position.
> 
> There are some references about this bug in [Perennial](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/190) and [Notional](https://github.com/sherlock-audit/2023-03-notional-judging/issues/203)

When the protocol activates the "defensive mode", most activities should be paused, especially adding new or expanding the current position, adding additional fund, etc. In another word, the system should be in "reduce-only" mode. Just like GME in 2021, robinhood announced a "reduce-only" mode.
https://www.fxstreet.com/news/gamestop-gme-tumbles-over-25-as-robinhood-puts-shares-on-reduce-only-mode-202101281424

It's more of a design choice, not bug.

**Comment by 0xbepresent** [comment]
I'm not sure why this issue it is considered a design choice and the next one https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146 is not considered a design choice, the team specify: *For this protocol, the team wants to have a "redundant" liquidation system to act as plan B, to protect the entire system, it's about risk management.*.

Thanks!

**Comment by 141345** [comment]
> I'm not sure why this issue it is considered a design choice and the next one #146 is not considered a design choice, the team specify: _For this protocol, the team wants to have a "redundant" liquidation system to act as plan B, to protect the entire system, it's about risk management._.
> 
> Thanks!

Actually I think https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146 is also a design choice of backup liquidation system, but the mechanism might not work as expected, it could lead to protocol's loss when the market has a bad day, and unluckily the team's bots are down.

For this report, yes I admit that the protocol's rule might be too strict, the user experience could be not that smooth. Pause all the assets if anything goes wrong seems quite defensive or sensitive. Maybe users could feel better if it's more flexible. 
But at the end, it's up to the protocol whether to go strict or loose. The spectrum is very wide, there exist very conservative protocols, and also protocols with loose rules.

Moreover, when the protocol in normal daily operation, users should learn the platform's rule in advance (knowing the possibility of the defensive mode), and prepare for the potential "enforced stop loss".

To sum up, the details of this mode might have room for improvement, but not a bug.

PS:
https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/106 is also about the defensive mode, but the issue is not about the mode itself, it's about the triggering mechanism of the mode.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is a design decision, additional context from the Sponsor:
> if system went into defensive mode something went wrong that shouldn't have happened. Until this is reviewed we don't want users to put more funds into the protocol. add_margin is still available with any funds that are already in the system, but otherwise system should be in winddown mode reducing potential exposure.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xbepresent](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/128/#issuecomment-1644631311): rejected
