### ISSUE TITLE
twicek - Regular users are not incentivized to liquidate

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-unstoppable-judging#146]
twicek

medium

# Regular users are not incentivized to liquidate

## Summary
Liquidation penalty fee is distributed between LPs and the protocol even when an external actor calls the function.

## Vulnerability Detail
Keeper bots are supposed to execute liquidations when positions are unhealthy, but anyone can perform a liquidation. In fact, only the protocol via its keeper bots is incentivized to perform liquidation since reward are only distributed to LPs and the protocol:

[Vault.vy#L346-L373](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L346-L373)
```solidity
def liquidate(_position_uid: bytes32):
				...
        self._distribute_trading_fee(position.debt_token, penalty)
```

[Vault.vy#L1342-L1356](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1342-L1356)
```solidity
def _distribute_trading_fee(_token: address, _amount: uint256):
    """
    @notice
        Distributes _amount of _token between LPs and protocol.
    """
    amount_for_lps: uint256 = _amount * self.trading_fee_lp_share / PERCENTAGE_BASE
    amount_for_protocol: uint256 = _amount - amount_for_lps


    if amount_for_lps > 0:
        self._pay_interest_to_lps(_token, amount_for_lps)
        log TradingFeeDistributed(0x0000000000000000000000000000000000000001, _token, amount_for_lps) # special address logged to signal LPs
    
    if amount_for_protocol > 0:
        self._safe_transfer(_token, self.protocol_fee_receiver, amount_for_protocol)
        log TradingFeeDistributed(self.protocol_fee_receiver, _token, amount_for_protocol)
```

If a regular user wants to liquidate an unhealthy position, he will not receive any rewards for doing so. Even a LP will only receive rewards diluted between all LPs and the protocol which is not enough of an incentive.

## Impact
Protocol Keepers are the only actors incentivized to liquidate unhealthy positions. Any issue in the keeper monitoring service availability could lead to positions aggregating bad debt.

## Code Snippet
[Vault.vy#L1342-L1356](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/contracts/margin-dex/Vault.vy#L1342-L1356)

## Tool used

Manual Review

## Recommendation
Consider rewarding the liquidator fully when it is not a keeper bot.

**Comment by 0xDE-GEN** [comment]
Escalate
I think this issue does not cause loss and should be considered a valid low.

> Q: Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, input validation expectations, etc)?
Keepers monitoring positions and executing orders and liquidations.

The contest page states that the keeper bot works as above, which means that the liquidation is done by the protocol.

The lack of incentive for regular users is a design pattern issue, which I think is valid low.

**Comment by sherlock-admin2** [comment]
> Escalate
> I think this issue does not cause loss and should be considered a valid low.
> 
> > Q: Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, input validation expectations, etc)?
> Keepers monitoring positions and executing orders and liquidations.
> 
> The contest page states that the keeper bot works as above, which means that the liquidation is done by the protocol.
> 
> The lack of incentive for regular users is a design pattern issue, which I think is valid low.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by twicek** [comment]
Escalate for 10 USDC
- The above escalation assumes that the keeper bots will never go offline, which is naive. There is always a risk that keeper bots go offline, especially if only the protocol team maintains them. In this case a mechanism should be in place as a fail-safe.
- The sponsor acknowledged the necessity to strengthened the liquidation setup.
- If there is no incentive for external actors or if the liquidation setup is not resilient enough, it will lead to insolvency for the protocol.

**Comment by sherlock-admin2** [comment]
> Escalate for 10 USDC
> - The above escalation assumes that the keeper bots will never go offline, which is naive. There is always a risk that keeper bots go offline, especially if only the protocol team maintains them. In this case a mechanism should be in place as a fail-safe.
> - The sponsor acknowledged the necessity to strengthened the liquidation setup.
> - If there is no incentive for external actors or if the liquidation setup is not resilient enough, it will lead to insolvency for the protocol.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xDE-GEN** [comment]
I'm not saying this shouldn't be fixed. 
I sympathize with the problem, but I think it's unreasonable to assume that the keeper bot can be offline, even though it says it works.

We need to recognize that just because the team feels the need to address it doesn't mean it's a valid vulnerability.

**Comment by twicek** [comment]
The point is not solely that the protocol acknowledges it. In my escalation, there is 3 points.

**Comment by 141345** [comment]
Recommendation: 
keep the original judging.


> Escalate I think this issue does not cause loss and should be considered a valid low.
> 
> > Q: Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, input validation expectations, etc)?
> > Keepers monitoring positions and executing orders and liquidations.
> 
> The contest page states that the keeper bot works as above, which means that the liquidation is done by the protocol.
> 
> The lack of incentive for regular users is a design pattern issue, which I think is valid low.

The protocol implements such "redundant" liquidation mechanism, trying to help maintain the system healthy state. However the current mechanism does not motivate normal users to participate, deviating from the design purpose.

The context for potential loss should not assume that everything works fine, the LP and protocol / team will always do the work. The context of the "redundant" liquidation system is when the above temperaily off and fail, that's when backup system comes. This report points out that the backup system might work as expected, it cannot attract normal users to help liquidating. So the mechanism needs imporovement.

I think it is a valid medium.

**Comment by 141345** [comment]
> Escalate for 10 USDC
> 
> * The above escalation assumes that the keeper bots will never go offline, which is naive. There is always a risk that keeper bots go offline, especially if only the protocol team maintains them. In this case a mechanism should be in place as a fail-safe.
> * The sponsor acknowledged the necessity to strengthened the liquidation setup.
> * If there is no incentive for external actors or if the liquidation setup is not resilient enough, it will lead to insolvency for the protocol.

same as above

**Comment by chainNue** [comment]
Not really sure why a design recommendation is being a Medium issue. Isn't this a design choice of the protocol? moreover the contest page also mention about keepers bot

as sponsor [said](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650):
> we believe it is more likely to achieve a healthy, redundant liquidation system by relying on the actors with intrinsic motivation to keep the system healthy - protocol, LPs, community/UND stakers.

Any user can freely liquidate positions to keep the healthy of the protocol, but if they're not being incentivized, it's a protocol choice. 

The counter escalation assume the keeper bot can goes offline, which is out of scope, but we can also assume the protocol will use multiple layers of bot / monitoring.

---

The recommendation of 
> Consider rewarding the liquidator...

is more like a suggestion, not an issue

**Comment by 141345** [comment]
> Not really sure why a design recommendation is being a Medium issue. Isn't this a design choice of the protocol? moreover the contest page also mention about keepers bot
> 
> as sponsor [said](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650):
> 
> > we believe it is more likely to achieve a healthy, redundant liquidation system by relying on the actors with intrinsic motivation to keep the system healthy - protocol, LPs, community/UND stakers.
> 
> Any user can freely liquidate positions to keep the healthy of the protocol, but if they're not being incentivized, it's a protocol choice.
> 
> The counter escalation assume the keeper bot can goes offline, which is out of scope, but we can also assume the protocol will use multiple layers of bot / monitoring.
> 
> The recommendation of
> 
> > Consider rewarding the liquidator...
> 
> is more like a suggestion, not an issue

For this protocol, the team wants to have a "redundant" liquidation system to act as plan B, to protect the entire system, it's about risk management. 

As opposite to other DeFi scenario like: reward the LP, airdrop, etc.. Those are more like extra bonus, which are different in this context. My point is, from aspect of rick control, the "rewards/incentive" here is totally differnt from the "LP reward" as a plus.

**Comment by chainNue** [comment]
> For this protocol, the team wants to have a "redundant" liquidation system to act as plan B, to protect the entire system, it's about risk management.

But, from my interpretation of the team [comment](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650), I still think that this non-incentive liquidator is an expected design.
> ... relying on the actors with intrinsic motivation to keep the system healthy

(Intrinsic motivation is to make the protocol healthy, an extrinsic motivation would be the monetary incentive when liquidating)

Thus this issue might fall into a "design improvement" category, which is [not a valid medium issue](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-not-considered-valid). In some other past contest, this similar "redundant" system, (like a "redundant" oracle system), doesn't fall into a medium issue. 

Let Sherlock judge decide this.

**Comment by twicek** [comment]
I understand why there is a lot of controversy on this one because it looks like a design suggestion, so I just want to give my last input.

Firstly, some comments are mixing what is in the [README](https://github.com/sherlock-audit/2023-06-unstoppable) with what has been said after the contest [e.g.](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/128#issuecomment-1648216113).

The information provided before the contest in the README was:
> Q: Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, input validation expectations, etc)?
Keepers monitoring positions and executing orders and liquidations.

And a second [README](https://github.com/sherlock-audit/2023-06-unstoppable/blob/main/unstoppable-dex-audit/README.md) inside the repos had additional informations.

Therefore, the only actors expected to execute liquidations where the protocol team.

The point of my report is to show that the liquidation setup as it is described in the README is not resilient enough since it does not have a resilient fail-safe mechanism if the protocol's keeper bots are offline. Rewarding independent/users actors when they liquidate cannot harm the protocol and add an additional layer of security.

This issue is far from being the most important one and considering the sponsor comment they seem confident in their own internal/community liquidation setup. However, I would never have written this report if I considered it a "design suggestion". Given the context we had during the contest, not rewarding external actors for liquidation centralize the execution of liquidations, which is a real risk that deserves medium severity.

I might have missed informations, so I'm happy to be wrong if this is the case.

**Comment by 141345** [comment]
> > For this protocol, the team wants to have a "redundant" liquidation system to act as plan B, to protect the entire system, it's about risk management.
> 
> But, from my interpretation of the team [comment](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650), I still think that this non-incentive liquidator is an expected design.
> 
> > ... relying on the actors with intrinsic motivation to keep the system healthy
> 
> (Intrinsic motivation is to make the protocol healthy, an extrinsic motivation would be the monetary incentive when liquidating)
> 
> Thus this issue might fall into a "design improvement" category, which is [not a valid medium issue](https://docs.sherlock.xyz/audits/judging/judging#list-of-issue-categories-that-are-not-considered-valid). In some other past contest, this similar "redundant" system, (like a "redundant" oracle system), doesn't fall into a medium issue.
> 
> Let Sherlock judge decide this.

The controversy of this report focus on whether the liquidation award is:
- "design improvement" for regular users
or
- "important component" for the protocol

My understanding, the additional liquidation mechanism is for the protocol to manage risk, rather than provide additional income for users. The incentive rewards is the "means", not the "goal". So it's far beyond "better user experience".

**Comment by chainNue** [comment]
again, quoting another protocol's [comment](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/39#issuecomment-1630867287):
> ... design choice of not rewarding external searchers for executing liquidations. While it was a conscious decision this is a valid discussion.

it's protocol design choice with conscious decision. The "conscious decision" means they fully aware of the options, consequences, and potential outcomes before arriving at their choice. 

By providing info in README about the existence of keeper bot, it's natural to have assumption the protocol will maintain its availability. For sure the protocol team understand clearly if the keeper bot is offline the liquidation will have issues, but they still keep on the decision of not rewarding the external liquidator, which means the keeper 'downtime' arguably is in acceptable rate. IMO, this issue is not a novel finding in which protocol (might) overlooked. 

Somehow, it's quite similar case with a recommendation of adding backup Teller oracle, when assuming Chainlink oracle can be offline (or returning false output). I recall the issue of redundant Oracle (I forgot in which contest) is low/informational due to protocol choice, as they choose to depends only on one oracle, while in fact oracle is critical and "important component".

**Comment by Unstoppable-DeFi** [comment]
I also want to highlight again a point that this discussion hasn’t really taken into consideration.

The infrastructure needed to monitor all open positions, price changes and effective leverage is fairly complex and assuming that some unspecified “MEV” entities would actually do this reliably and with better redundancy for a potential but not guaranteed payoff is in our opinion a fairly unfounded and dangerous assumption to make - and the core reason for our design choice of approaching this another way.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Although I appreciate the discussion above, this issue is a valid low. This is clearly a design implementation. 
https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146#issuecomment-1641735650
> There is always a risk that keeper bots go offline

Since the liquidation is handled by the protocol. This is an admin error. Not a valid high/medium. 
Additionally, 
https://docs.unstoppable.ooo/unstoppable/products/unstoppable-dex/liquidations

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [dot-pengun](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146/#issuecomment-1642997415): accepted
- [twicek](https://github.com/sherlock-audit/2023-06-unstoppable-judging/issues/146/#issuecomment-1643839754): rejected
